kind = "web"
previewPath = "/"
title = "British Bulldog NFT"
version = "1.0.0"
id = "artifacts/bbulldog"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24564

[services.development]
run = "pnpm --filter @workspace/bbulldog run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/bbulldog", "run", "build" ]
publicDir = "artifacts/bbulldog/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24564"
BASE_PATH = "/"
